jobs:
  - template: ../../azure-pipelines/jobs/run-tests.yml
    parameters:
      serviceName: ci-internal-api-php-client
      variables:
        CLOUD_PROVIDER: aws
        STORAGE_API_URL: $(STORAGE_API_URL__AWS)
      secrets:
        STORAGE_API_TOKEN: $(INTERNAL_API_PHP_CLIENT__STORAGE_API_TOKEN__AWS)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
