pool:
  name: 'Default'

steps:
- script: docker info
  displayName: 'Info'

- script: docker-compose build --no-cache --pull
  displayName: 'Build Tests'

- script: docker pull keboola/docker-job-queue-internal-api
  displayName: 'Pull Images'

- script: docker-compose run --rm tests
  displayName: 'Run Tests'
  env:
    TEST_STORAGE_API_URL: $(TEST_STORAGE_API_URL)
    TEST_STORAGE_API_TOKEN: $(TEST_STORAGE_API_TOKEN)
    TEST_KMS_KEY_ALIAS: $(TEST_KMS_KEY_ALIAS)
    TEST_KMS_REGION: $(TEST_KMS_REGION)
    TEST_AWS_ACCESS_KEY_ID: $(TEST_AWS_ACCESS_KEY_ID)
    TEST_AWS_SECRET_ACCESS_KEY: $(TEST_AWS_SECRET_ACCESS_KEY)
