pool:
  vmImage: 'ubuntu-latest'

steps:
- script: docker info
  displayName: 'Info'

- script: docker build -t job-queue-internal-api-php-client .
  displayName: 'Build Tests'

- script: docker run job-queue-internal-api-php-client composer ci
  displayName: 'Run Tests'
