pool:
  vmImage: ubuntu-latest

pr: none
trigger:
  batch: true
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

steps:

- task: Docker@2
  displayName: Test ACR login
  inputs:
    command: login
    containerRegistry: 'Keboola PS Test ACR'

- script: |
    docker-compose down
    docker-compose build --pull
    docker-compose pull
  displayName: 'Build Tests'

- script: docker-compose run --rm tests
  displayName: 'Run Tests'
  env:
    TEST_STORAGE_API_URL: $(TEST_STORAGE_API_URL)
    TEST_STORAGE_API_TOKEN: $(TEST_STORAGE_API_TOKEN)
    TEST_KMS_KEY_ALIAS: $(TEST_KMS_KEY_ALIAS)
    TEST_KMS_REGION: $(TEST_KMS_REGION)
    TEST_AWS_ACCESS_KEY_ID: $(TEST_AWS_ACCESS_KEY_ID)
    TEST_AWS_SECRET_ACCESS_KEY: $(TEST_AWS_SECRET_ACCESS_KEY)
    TEST_AZURE_CLIENT_ID: $(TEST_AZURE_CLIENT_ID)
    TEST_AZURE_CLIENT_SECRET: $(TEST_AZURE_CLIENT_SECRET)
    TEST_AZURE_TENANT_ID: $(TEST_AZURE_TENANT_ID)
    TEST_AZURE_KEY_VAULT_URL: $(TEST_AZURE_KEY_VAULT_URL)
    TEST_QUEUE_API_TOKEN: $(TEST_QUEUE_API_TOKEN)
