version: "2"
services:
  # for development purposes
  dev:
    build: .
    volumes:
        - ./:/code
    environment:
      - "TEST_QUEUE_API_URL"
      - "TEST_STORAGE_API_URL"
      - "TEST_STORAGE_API_TOKEN"
      - "TEST_KMS_KEY_ALIAS"
      - "TEST_KMS_REGION"
      - "TEST_AWS_ACCESS_KEY_ID"
      - "TEST_AWS_SECRET_ACCESS_KEY"
