version: "2"
services:
  # for development purposes
  tests: &tests
    build: .
    environment:
      - TEST_QUEUE_API_URL=http://internal-api:3000
      - TEST_STORAGE_API_URL
      - TEST_STORAGE_API_TOKEN
      - TEST_KMS_KEY_ALIAS
      - TEST_KMS_REGION
      - TEST_AWS_ACCESS_KEY_ID
      - TEST_AWS_SECRET_ACCESS_KEY
    depends_on:
      - internal-api
    networks:
      - internal-api-client
    command: ["/code/docker/phpunit.sh"]

  tests-local:
    <<: *tests
    volumes:
      - ./:/code

  internal-api:
    image: keboolapes.azurecr.io/job-queue-internal-api:latest
    ports:
      - "80:80"
    volumes:
      - ./:/build-code
      - ./var:/code/var
    environment:
      - log_abs_connection_string=
      - log_abs_container=debug-files
      - logs_s3_bucket=
      - logs_s3_bucket_region=
      - MYSQL_ROOT_PASSWORD=root
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_NAME=jobs

    command: ['sh', '-c', '/build-code/docker/wait-for-it.sh --strict --timeout=120 mysql:3306 -- php bin/console doctrine:migrations:migrate && apache2-foreground']
    networks:
      - internal-api-client
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=jobs
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - internal-api-client

networks:
  internal-api-client:
